version: "3"

services:
  database:
    image: mariadb
    # volumes:
    #   - ./beertaste/data/db:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: beeeeeer
      MARIADB_PASSWORD: beeeeeer
      MARIADB_USER: beer
      MARIADB_DATABASE: drinkder
      MARIADB_PORT: 3306
    networks:
      beer:
        ipv4_address: 10.10.10.12
    expose:
      - 3306

  django:
    build:
      context: ./beertaste/
    volumes:
      - ./beertaste/:/usr/src/app
    command: >
      sh -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py loaddata beerdata.json &&
      python3 manage.py collectstatic &&
      gunicorn beertaste.wsgi"
    environment:
      DATABASE_PASS: beeeeeer
      DATABASE_USER: beer
      DATABASE_NAME: drinkder
      DJANGO_SECRET: jdfhasdf89asuf09sduaf9
    networks:
      beer:
        ipv4_address: 10.10.10.11
    expose:
      - 8000
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    command: >
      sh -c "mkdir -p /var/www/media &&
      mkdir -p /var/www/static"
    networks:
      beer:
        ipv4_address: 10.10.10.10
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./beertaste/static/:/var/www/static/
      - ./beertaste/media/:/var/www/media/
    depends_on:
      - django
      - database

networks:
  beer:
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"
