version: "3"

services:
  database:
    image: mariadb
    volumes:
      - ./beertaste/data/db:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: beeeeeer
      MARIADB_USER: beer
      MARIADB_DATABASE: drinkder

  django:
    build:
      context: ./beertaste/
    volumes:
      - ./beertaste/:/usr/src/app
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py loaddata beerdata.json &&
      python manage.py collectstatic &&
      uwsgi --ini container_uwsgi.ini"
    environment:
      DATABAE_PASS: beeeeeer
      DATABAE_USER: beer
      DATABASE_NAME: drinkder
      DJANGO_SECRET: fuck docker
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
