# Generated by Django 4.1 on 2022-10-17 20:26

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfBeer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='beerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=200)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('image', stdimage.models.JPEGField(force_min_size=False, upload_to='images/', validators=[stdimage.validators.MinSizeValidator(400, 400)], variations={'thumbnail': (400, 400, True)})),
                ('drank_date', models.DateTimeField(auto_now_add=True, verbose_name='data published')),
                ('description', models.CharField(max_length=300)),
                ('adjectives', models.ManyToManyField(to='sites.tags')),
                ('beer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.mold')),
                ('countryMade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.country')),
            ],
        ),
    ]
