# Generated by Django 4.1 on 2022-09-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='beerreview',
            name='adjectives',
            field=models.ManyToManyField(to='sites.tags'),
        ),
        migrations.AddField(
            model_name='beerreview',
            name='countryMade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.country'),
        ),
    ]
