# Generated by Django 4.1 on 2022-09-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_country_tags_alter_beerreview_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfBeer', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='beerreview',
            name='beer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.mold'),
        ),
    ]
