# Generated by Django 4.1 on 2022-10-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_mold_beerreview_beer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
