# Generated by Django 4.1 on 2022-10-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_beerreview_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='adjectives',
            field=models.ManyToManyField(null=True, to='sites.tags'),
        ),
    ]
